---
# Example config file
livenessProbe:
  enabled: true
  path: /_meta/health
readinessProbe:
  enabled: true
  path: /_meta/ready
broadcasts:
  - source:
      connectionString: amqp://user:secret@localhost:5672
      exchange: MQ.Topic.Source.Exchange
      routingKey: MQ.RoutingKey
      bmqQueueName: BMQ.Queue.Broadcaster.1
    destination:
      connectionString: amqp://user:secret@localhost:35672
      bmqExchange: BMQ.Topic.Dest.Exchange
      bmqRoutingKey: BMQ.APP.RoutingKey.Example.#
      persistHeaders: true
      queues:
        - name: MQ.Queue.Destination.Example.1
          bmqBindingKey: BMQ.BindingKey.Example.1
        - name: MQ.Queue.Destination.Example.2
          bindingKey: MQ.BindingKey.Example.2
          keepHeaders: true
        - name: MQ.Queue.Destination.Example.3
          bindingKey: MQ.BindingKey.Example.3
  - source:
      connectionString: amqp://user:secret@localhost:35672
      exchange: MQ.Topic.Source.Exchange
      routingKey: MQ.RoutingKey
    destination:
      connectionString: amqp://user:secret@localhost:5672
      queues:
        - name: MQ.Queue.Destination.Example
          bindingKey: MQ.BindingKey.Example
